version: '2'

services:

  redux-hist-react:
    build:
      context: .
      dockerfile: Dockerfile
      encrypted_args_file: secret.env.encrypted
    volumes:
      - .git:/redux-hist-react/.git
    encrypted_env_file: secret.env.encrypted
    cached: true
